### ISSUE TITLE
Should lastResolve allow for a list of observers?

### ISSUE THREAD

**Issue by mmocny** [uxify-ltd/performance-event-timing-polyfill#1]
I like that any new event listener firing will resolve any active listener of `nextTick` via the `lastResolve()` event.

However, I think that whenever there are multiple callers to `measurePresentationDelay` from a single animation frame, there will be multiple callers to `nextTick`, back to back.  That means you will overwrite the `lastResolve` value (and so only the last caller will get notified).

I think!

Perhaps consider changing to a list of callbacks?  Or, replace the callback(s) with a Promise (where you can have any number of .then()), where the promise is reset after each new event.  Or, create an EventTarget object, so you can have any number of `addEventListener(, { once: true })`.

**Comment by ivailo-uxify** [comment]
Thanks!

`measurePresentationDelay` has this guard to prevent calling `nextTick` back to back https://github.com/uxify-ltd/performance-event-timing-polyfill/blob/af22eb55facf30873e3d06fe87afe6e809f284a2/src/eventObserver.ts#L122 

However currently only the last event, which began within the frame, will get its presentation delay calculated. This is about to change with an upcoming update where `scheduledFrames[currentFrameStart]` will become a list, so that all events from the same frame will get these times calculated.

Let me know if that makes sense or there is still a need to make `lastResovle()` a list of callbacks.

**Comment by ivailo-uxify** [comment]
Resolving this for now. Feel free to open a new one if you have further input on this.
